### ISSUE TITLE
CSL JSON export fails when extra field exists

### ISSUE THREAD

**Issue by dhimmel** [zotero/zotero#1604]
CSL JSON export fails when the Zotero data field `extra` is set. Omitting extra or setting it blank bypasses the issue. I believe the most relevant error message is:

```
TypeError: Cannot read property 'extraToCSL' of undefined
```

## Reproducible examples

The examples use curl calls to our `translation-server` instance. The JSON data below is saved in a file named `zotero-data.json`. Then the following curl command is used:

```bash
curl \
 --header "Content-Type: application/json" \
 --data @zotero-data.json \
 'https://translate.manubot.org/export?format=csljson'
```

### Fails

The following JSON files fail. The first `extra` field is an actual value returned by Zotero when retrieving metadata for the URL `https://github.com/greenelab/manubot`.

```json
[{
    "extra": "original-date: 2017-06-29T15:02:20Z",
    "itemType": "computerProgram"
}]
```

```json
[{
    "extra": "test",
    "itemType": "computerProgram"
}]
```

### Passes

```json
[{
    "extra": "",
    "itemType": "computerProgram"
}]
```

```json
[{
    "itemType": "computerProgram"
}]
```

## Full stacktrace

Here is the translation-server stderr output. It was a bit hard to know where each failure message starts / stops and the logs were repetitive. But I think this captures every unique message:

```
(node:1038) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'extraToCSL' of undefined
    at Zotero.Utilities.Translate.itemToCSLJSON (/home/translate/translation-server/modules/zotero/chrome/content/zotero/xpcom/utilities.js:1607:27)
    at Function.itemToCSLJSON (/home/translate/translation-server/src/translation/sandboxManager.js:94:17)
    at doExport (eval at <anonymous> (/home/translate/translation-server/src/translation/sandboxManager.js:68:4), <anonymous>:111:43)
    at Zotero.Translate.Export.rest (/home/translate/translation-server/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1396:49)
    at loadPromise.then (/home/translate/translation-server/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1386:39)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:1038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 95)

  SyntaxError: Unexpected token } in JSON at position 74
      at JSON.parse (<anonymous>)
      at parse (/home/translate/translation-server/node_modules/co-body/lib/json.js:57:17)
      at AsyncFunction.module.exports [as json] (/home/translate/translation-server/node_modules/co-body/lib/json.js:41:20)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by dhimmel** [comment]
`extraToCSL` appears to be called here

https://github.com/zotero/zotero/blob/e48a1a2abb2384f329b57b7946e757a543076d13/chrome/content/zotero/xpcom/utilities.js#L1606-L1608

Here's the actual function, which I suppose is failing:

https://github.com/zotero/zotero/blob/e48a1a2abb2384f329b57b7946e757a543076d13/chrome/content/zotero/xpcom/cite.js#L320-L417

**Comment by adam3smith** [comment]
Pretty sure this is specific to the translation server. This works fine for me in Zotero proper (and we´d be seeing way more error reports since citations rely on CSL JSON export). Doesn´t make it less of a bug, but I think this should probably be moved.

**Comment by dhimmel** [comment]
Thanks @dstillman for the fix in https://github.com/zotero/translation-server/commit/517e2644d9b5e5e3b0180599565effb4c3f5cb82. So was the issue that the zotero submodule had gotten outdated?

**Comment by dhimmel** [comment]
Confirming that the issue is now fixed on https://translate.manubot.org which is current running https://github.com/zotero/translation-server/commit/8b8355a7acf1fa3252141b108cc61c377679af19. The only tricky thing was that we had to specify `--recurse-submodules`, when doing `git pull` to update the zotero submodule.
