### ISSUE TITLE
"Error: getTranslators: detection is already running" when localhost web development 

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [zotero/zotero#3091]
I usually have Zotero disabled on localhost when creating a React or Vue app but, when it is enabled, this error appears in the console.
```
caught (in promise) Error: getTranslators: detection is already running
    at Zotero.Translate.Web.<anonymous> (translate.js:1091:45)
    at Zotero.Translate.Web.getTranslators (promise.js:36:17)
    at Object.init (inject.js:106:25)
```

**Comment by dstillman** [comment]
I'm not really sure what you're reporting here. Can you provide <a href="https://www.zotero.org/support/reporting_problems#provide_steps_to_reproduce">Steps to Reproduce</a>?

**Comment by asmaloney** [comment]
Just another data point: I'm getting this on my local dev environment as well. I'm running vue 2.7.14 in docker on a Mac.
